#!/bin/sh

echo Loading shell environment ... >&2

# Set my Git user details.
gitme() {
    git config user.name "Susam Pal"
    git config user.email susam@susam.net
    git config user.name
    git config user.email
}

# Clone GitHub repository.
ghclone() {
    cd ~/git
    pwd
    if [ $# -eq 1 ]
    then
        git clone "https://github.com/susam/$1.git"
        cd "$1"
    else
        git clone "https://github.com/$1/$2.git"
        cd "$2"
    fi
    pwd
}

# OCR PDFs.
ocr()
{
    for f in "$@"
    do
        echo "OCRing $f ..."
        ocrmypdf "$f" "${f%.pdf}-ocr.pdf"
        mv "$f" "$f.bkp"
        mv "${f%.pdf}-ocr.pdf" "$f"
        ls -lh "$f.bkp"
        ls -lh "$f"
    done
}

# Redshift
red()
{
    case $1 in
        off)
            pkill redshift
            ;;
        [0-9]*)
            pkill redshift
            pkill redshift
            redshift -v -l 0:0 -t $1:$1 > ~/redshift.log 2>&1 &
            ;;
        bed)
            pkill redshift
            pkill redshift
            redshift -v -l 13:77 -t 3400:1900 > ~/redshift.log 2>&1 &
            ;;
        "")
            pkill redshift
            pkill redshift
            redshift -v -l 13:77 -t 5000:3400 > ~/redshift.log 2>&1 &
            ;;
        *)
            echo 'Usage: red [off | bed | <temperature>]' >&2
            ;;
    esac
}

# Search texlive for file
findtl()
{
    find /usr/local/texlive -name "*$1*"
}

# Set environment.
PATH=~/bin:$PATH
[ -f ~/my/bin/env ] && . ~/my/bin/env

_begin_esc()
{
    [ -n "$BASH_VERSION" ] && printf '\x01' && return
    [ -n "$ZSH_VERSION" ] && printf '%%{' && return
}

_end_esc()
{
    [ -n "$BASH_VERSION" ] && printf '\x02' && return
    [ -n "$ZSH_VERSION" ] && printf '%%}' && return
}

# Set terminal color.
_tput_color()
{
    _begin_esc
    tput setaf "$1"
    _end_esc
}

# Reset terminal color.
_tput_reset()
{
    _begin_esc
    tput sgr0
    _end_esc
}

# Create dynamic prompt string for PS1.
_active_prompt()
{
    # Git branch
    git_branch=$(git branch 2> /dev/null | sed -n "s/^\* *//p")
    if [ -n "$git_branch" ]
    then
        _tput_color 148 # yellow
        printf '[%s] ' "$git_branch"
    fi
    unset git_branch

    # Docker machine name
    if [ -n "$DOCKER_MACHINE_NAME" ]
    then
        _tput_color 80 # blue
        printf '[%s] ' "$DOCKER_MACHINE_NAME"
    fi

    # Current directory
    if [ "$PWD" != "$HOME" ]
    then
        if printf '%s' "$PWD" | grep -q "^$HOME"
        then
            neat_path="~${PWD#$HOME}"
        else
            neat_path=$PWD
        fi
        _tput_color 2 # green
        printf '%s' "$neat_path"
        unset neat_path 
    fi

    # Dollar or beer sign
    _tput_color 172 # orange
    if [ -n "$_PROMPT_MARK" ]
    then
        printf '%s' "$_PROMPT_MARK"
    elif [ $(date +"%a") = Fri ]
    then
        printf '%s' "$_beer "
    elif [ $(date +"%a") = Sat ]
    then
        printf '%s' "$_beer$_beer "
    else
        printf '$ '
    fi
    _tput_reset
}

# Aliases to modify the ending characters of the primary prompt.
_beer=$(printf "\xf0\x9f\x8d\xba")
alias dollar='_PROMPT_MARK="$ "'
alias beer='_PROMPT_MARK="$_beer "'
alias beer2='_PROMPT_MARK="$_beer$_beer "'

# Aliases for Transmission CLI.
alias txd='transmission-daemon -f'
alias txa='transmission-remote -t all'
alias txr='transmission-remote'
alias tx='transmission-remote'

# Aliases for Common Lisp.
alias cl='sbcl --noinform --quit --load'

args() {
    for arg in "$@"
    do
        echo "arg: \"$arg\""
    done
}

alias c++11="c++ -g -std=c++11 -Wall -Wextra -pedantic"

ec() {
    emacsclient "$@"
}

em() {
    if [ "$#" -eq 0 ]
    then
        echo "Starting new Emacs process ..." >&2
        emacs & disown
    elif emacsclient -n "$@" 2> /dev/null
    then
        echo "Opened $@ in Emacs server" >&2
    else
        echo "Opening $@ in a new Emacs process ..." >&2
        emacs "$@" & disown
    fi
}

# Set the primary prompt string.
PS1='$(_active_prompt)'

# For specific shells only.
if [ -n "$BASH_VERSION" ]
then
    echo Loading Bash environment ... >&2

    [ -r "/usr/local/etc/profile.d/bash_completion.sh" ] &&
       . "/usr/local/etc/profile.d/bash_completion.sh"
elif [ -n "$ZSH_VERSION" ]
then
    echo Loading ZSH environment ... >&2
    setopt prompt_subst
    autoload bashcompinit && bashcompinit
    autoload compinit && compinit
fi

# Attach to an existing Screen session or launch a new one.
# [ -n "$STY$TMUX" ] || screen -dRR

# Attach to an existing tmux or a launch new tmux.
[ -n "$STY$TMUX" ] || tmux at || tmux

echo Done >&2
